eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  main:
    web-application-type: reactive
  application:
    name: Gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: interactions
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/interactions/**


        - id: comments
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/comments/**


        - id: shareds
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/shareds/**


        - id: reactions
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/reactions/**


        - id: users-auth
          uri: http://localhost:8101
          predicates:
            - Path=/api/v1/auth/**

        - id: users-data
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/**


        - id: medias
          uri: http://localhost:8016
          predicates:
            - Path=/api/v1/medias/**


        - id: friend-services
          uri: http://localhost:8078
          predicates:
            - Path=/api/friend/**


        - id: post-services
          uri: http://localhost:8074
          predicates:
            - Path=/api/v1/post/**

    #/api/friend-requests
    discovery:
      enabled: true
    config:
      enabled: false


management:
  tracing:
    sampling:
      probability: 1.0





